//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetLoginProvider
    {
        public AspNetLoginProvider()
        {
            this.UserLogins = new HashSet<AspNetUserLogin>();
        }
    
        public byte LoginProviderId { get; private set; }
        public string Name { get; set; }
    
        public virtual ICollection<AspNetUserLogin> UserLogins { get; private set; }
    }
}
