//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserLogin
    {
        public int UserId { get; set; }
        public byte LoginProviderId { get; private set; }
        public long ProviderKey { get; set; }
        public string AccessToken { get; set; }
        public string AccessTokenSecret { get; set; }
    
        public virtual AspNetUser User { get; private set; }
        public virtual AspNetLoginProvider LoginProvider { get; set; }
    }
}
