//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.IsPlayerVerified = false;
            this.IsPlayerPublic = true;
            this.UserLogins = new HashSet<AspNetUserLogin>();
            this.Friends = new HashSet<AspNetUserFriend>();
        }
    
        public int Id { get; private set; }
        public Nullable<int> PlayerId { get; set; }
        public bool IsPlayerVerified { get; set; }
        public string PlayerVerifyToken { get; set; }
        public Nullable<System.DateTime> PlayerVerifyEndTime { get; set; }
        public bool IsPlayerPublic { get; set; }
    
        public virtual ICollection<AspNetUserLogin> UserLogins { get; set; }
        public virtual ICollection<AspNetUserFriend> Friends { get; private set; }
        public virtual Player Player { get; private set; }
        public virtual TwitterInfo TwitterInfo { get; set; }
    }
}
