//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateInfo
    {
        public DateInfo()
        {
            this.SenkaDatas = new HashSet<SenkaData>();
            this.Servers = new HashSet<Server>();
        }
    
        public int DateId { get; private set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<SenkaData> SenkaDatas { get; private set; }
        public virtual ICollection<Server> Servers { get; set; }
    }
}
