//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.SenkaDatas = new HashSet<SenkaData>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public byte ServerId { get; set; }
    
        public virtual ICollection<SenkaData> SenkaDatas { get; private set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual Server Server { get; set; }
    }
}
