//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenkaContext : DbContext
    {
        public SenkaContext()
            : base("name=SenkaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DateInfo> DateInfoes { get; set; }
        public virtual DbSet<SenkaData> SenkaDatas { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserFriend> AspNetUserFriends { get; set; }
        public virtual DbSet<AspNetLoginProvider> AspNetLoginProviders { get; set; }
        public virtual DbSet<TwitterInfo> TwitterInfoes { get; set; }
        public virtual DbSet<ServerAuthorize> ServerAuthorizes { get; set; }
    }
}
