//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SenkaData
    {
        public int DateId { get; internal set; }
        public int PlayerId { get; internal set; }
        public short Ranking { get; internal set; }
        public Nullable<short> RankingDelta { get; private set; }
        public short RankPoint { get; internal set; }
        public Nullable<short> RankPointDelta { get; private set; }
        public Nullable<int> Experience { get; internal set; }
        public Nullable<int> ExperienceDelta { get; private set; }
        public string Comment { get; internal set; }
        public byte Level { get; internal set; }
        public byte RankTypeId { get; internal set; }
        public short Medals { get; internal set; }
        public Nullable<short> RankingAll { get; set; }
    
        public virtual DateInfo DateInfo { get; private set; }
        public virtual Player Player { get; private set; }
    }
}
