//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerAuthorize
    {
        public byte ServerId { get; private set; }
        internal string Username { get; private set; }
        internal string Password { get; private set; }
        internal string IpAddress { get; set; }
        internal string Token { get; set; }
    
        public virtual Server Server { get; private set; }
    }
}
