//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerMaintenance
    {
        public int Id { get; private set; }
        public System.DateTime StartTime { get; internal set; }
        public System.DateTime EndTime { get; internal set; }
    }
}
