//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public byte ServerId { get; private set; }
        public string Name { get; private set; }
        public string NickName { get; private set; }
        public int LastUpdated { get; internal set; }
    
        public virtual DateInfo DateInfo { get; set; }
        public virtual ServerAuthorize ServerAuthorize { get; private set; }
    }
}
