//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterInfo
    {
        public int AspNetUserId { get; set; }
        public string ScreenName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string AvatarUrl { get; set; }
        public string BannerUrl { get; set; }
        public string UserSite { get; set; }
        public string UserSiteUrl { get; set; }
        public System.DateTime ProfileUpdateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
