//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenkaKichi.ManagementTool.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/SenkaKichi.WcfService")]
    public enum ServiceResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknowError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unavailable = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VerifyUserToken", ReplyAction="http://tempuri.org/IService/VerifyUserTokenResponse")]
        SenkaKichi.ManagementTool.ServiceReference.ServiceResult VerifyUserToken(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VerifyUserToken", ReplyAction="http://tempuri.org/IService/VerifyUserTokenResponse")]
        System.Threading.Tasks.Task<SenkaKichi.ManagementTool.ServiceReference.ServiceResult> VerifyUserTokenAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateServerIpAddress", ReplyAction="http://tempuri.org/IService/UpdateServerIpAddressResponse")]
        SenkaKichi.ManagementTool.ServiceReference.ServiceResult UpdateServerIpAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateServerIpAddress", ReplyAction="http://tempuri.org/IService/UpdateServerIpAddressResponse")]
        System.Threading.Tasks.Task<SenkaKichi.ManagementTool.ServiceReference.ServiceResult> UpdateServerIpAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSenkaData", ReplyAction="http://tempuri.org/IService/UpdateSenkaDataResponse")]
        SenkaKichi.ManagementTool.ServiceReference.ServiceResult UpdateSenkaData(int serverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSenkaData", ReplyAction="http://tempuri.org/IService/UpdateSenkaDataResponse")]
        System.Threading.Tasks.Task<SenkaKichi.ManagementTool.ServiceReference.ServiceResult> UpdateSenkaDataAsync(int serverId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SenkaKichi.ManagementTool.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SenkaKichi.ManagementTool.ServiceReference.IService>, SenkaKichi.ManagementTool.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SenkaKichi.ManagementTool.ServiceReference.ServiceResult VerifyUserToken(int userId) {
            return base.Channel.VerifyUserToken(userId);
        }
        
        public System.Threading.Tasks.Task<SenkaKichi.ManagementTool.ServiceReference.ServiceResult> VerifyUserTokenAsync(int userId) {
            return base.Channel.VerifyUserTokenAsync(userId);
        }
        
        public SenkaKichi.ManagementTool.ServiceReference.ServiceResult UpdateServerIpAddress() {
            return base.Channel.UpdateServerIpAddress();
        }
        
        public System.Threading.Tasks.Task<SenkaKichi.ManagementTool.ServiceReference.ServiceResult> UpdateServerIpAddressAsync() {
            return base.Channel.UpdateServerIpAddressAsync();
        }
        
        public SenkaKichi.ManagementTool.ServiceReference.ServiceResult UpdateSenkaData(int serverId) {
            return base.Channel.UpdateSenkaData(serverId);
        }
        
        public System.Threading.Tasks.Task<SenkaKichi.ManagementTool.ServiceReference.ServiceResult> UpdateSenkaDataAsync(int serverId) {
            return base.Channel.UpdateSenkaDataAsync(serverId);
        }
    }
}
